export default {
    plugins: ['prettier-plugin-organize-attributes', '@trivago/prettier-plugin-sort-imports'],
    overrides: [
        {
            files: ['*.vue'],
            options: {
                parser: 'vue',
            },
        },
    ],
    attributeGroups: [
        // 1. Vue Directives
        '^#',
        '^v-(if|else-if|else)$',
        '^v-model$',
        '^v-html$',
        '^v-text$',
        '^v-for$',
        '^v-bind$',
        '^v-show$',

        // 2. Prefixed prop bindings
        '^:is$',
        '^:ref$',
        '^:key$',
        '^:id$',
        '^:class$',
        '^:to$',
        '^:href$',
        '^:name$',
        '^:title$',
        '^:aria-label$',
        '^:label$',
        '^:type$',
        '^:tabindex$',
        '^:text$',
        '^:placeholder$',
        '^:variant$',
        '^:size$',
        '^:min$',
        '^:max$',
        '^:step$',
        '^:multiple$',
        '^:accept$',
        '^:position$',
        '^:placement$',
        '^:theme$',
        '^:icon$',
        '^:color$',
        '^:disabled$',
        '^:error$',
        '^:',

        // 3. Unprefixed prop bindings
        '^to$',
        '^href$',
        '^name$',
        '^title$',
        '^aria-label$',
        '^label$',
        '^type$',
        '^tabindex$',
        '^text$',
        '^placeholder$',
        '^variant$',
        '^size$',
        '^min$',
        '^max$',
        '^step$',
        '^accept$',
        '^multiple$',
        '^position$',
        '^placement$',
        '^theme$',
        '^icon$',
        '^color$',
        '^disabled$',
        '^error$',

        // 4. Default values
        '$DEFAULT',

        // 5. Events
        '^@',
    ],
    endOfLine: 'lf',
    htmlWhitespaceSensitivity: 'ignore',
    importOrder: [
        '^vue$',
        '<THIRD_PARTY_MODULES>',
        '^(.*)\\.(scss|css)$',
        '@/(App.vue$|router|i18n|locales)',
        '^(.*)/assets/(.*)$',
        '^(.*)/(components|modals)/(.*)$',
        '^(.*)/routes/(.*)$',
        '^(.*)/composables/(.*)$',
        '^(.*)/config/(.*)$',
        '^./(.*).config.js$',
        '^(.*)/constants/(.*)$',
        '^(.*)/events/(.*)$',
        '^(.*)/layouts/(.*)$',
        '^(.*)/locales/(.*)$',
        '^(.*)/services/(.*)$',
        '^(.*)/stores/(.*)$',
        '^(.*)/types/(.*)$',
        '^(.*)/utils/(.*)$',
        '^(.*)/views/(.*)$',
        '^[./]',
    ],
    importOrderSeparation: true,
    importOrderSortSpecifiers: true,
    printWidth: 130,
    semi: false,
    singleAttributePerLine: false,
    singleQuote: true,
    tabWidth: 4,
    trailingComma: 'all',
    useTabs: false,
    vueIndentScriptAndStyle: true,
}
