export default {
    attributeGroups: [
        '^#',
        '^v-tooltip$',
        '^:?is$',
        '^v-for$',
        '^v-(if|else-if|else)$',
        '^v-show$',
        '^v-cloak$',
        '^v-pre$',
        '^v-once$',
        '^:?id$',
        '^:?ref$',
        '^:?key$',
        '^v-model$',
        '^v-model:',
        '^:?class$',
        '^:(?!data-)',
        '$DEFAULT',
        '^:?data-',
        '^v-html$',
        '^v-text$',
        '^v-bind$',
        '^@',
    ],
    endOfLine: 'lf',
    htmlWhitespaceSensitivity: 'ignore',
    importOrder: [
        '<THIRD_PARTY_MODULES>',
        '^(.*)/config/(.*)$',
        '^(.*)/enums(.*)$',
        '^(.*)/locales/(.*)$',
        '^(.*)/types/(.*)$',
        '^(.*)/components/(.*)$',
        '^(.*)/stores/(.*)$',
        '^(.*)/services/(.*)$',
        '^(.*)/composables/(.*)$',
        '^(.*)/utils/(.*)$',
        '^[./]',
    ],
    importOrderSeparation: true,
    importOrderSortSpecifiers: true,
    plugins: [
        '@trivago/prettier-plugin-sort-imports',
        'prettier-plugin-organize-attributes',
        'prettier-plugin-tailwindcss',
    ],
    printWidth: 100,
    semi: false,
    singleAttributePerLine: false,
    singleQuote: true,
    tabWidth: 4,
    tailwindFunctions: ['clsx'],
    trailingComma: 'all',
    useTabs: false,
    vueIndentScriptAndStyle: true,
}
